### ISSUE TITLE
Inaccurate version bounds in  fn.cabal 

### ISSUE THREAD

**Issue by hvr** [dbp/fn#4]
Specifically, `fn.cabal` claims to be compatible with `base-4.7`, but evidently isn't:

```
[1 of 1] Compiling Web.Fn           ( src/Web/Fn.hs, dist/dist-sandbox-c5ec2f5c/build/Web/Fn.o )
src/Web/Fn.hs:103:34: Not in scope: ‘<$>’
src/Web/Fn.hs:476:27: Not in scope: ‘<$>’
src/Web/Fn.hs:482:27: Not in scope: ‘<$>’
```

please either add more accurate version bounds or make `fn` compatible with the version ranges stated in the `fn.cabal` file. Thanks!

**Comment by dbp** [comment]
@hvr Sorry about that! I just fixed this and released http://hackage.haskell.org/package/fn-0.2.0.2 with the fix. Additionally, I set up the build server to test both GHC 7.10 (which it was before) and GHC 7.8 (which it obviously wasn't before), so this shouldn't happen again.
